server:
  port: 8080
  servlet:
    context-path: /demo

spring:
#  resources:
#    static-locations: classpath:/static/
#
#  mvc:
#    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  datasource:
    username: iiva
    password: iiva
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000

logging:
  file:
    name: ../log/web/demo-web.log
